export const eTaskbarItemAnimation = {
  bounce: 0,
  flash: 1,
  pulse: 2,
  shakeX: 3,
  shakeY: 4,
  swing: 5,
  tada: 6,
  wobble: 7,
  jello: 8,
  out: 9
}

export const eSwarmConnectionState = {
  intial: 0,
  negotiating: 1,
  active: 2,
  closed: 3
};

export const eRTCConnectionState = {
  unknown: 0,
  new: 1,
  connecting: 2,
  connected: 3,
  disconnected: 4,
  failed: 5,
  closed: 6
};

export const eRTCSignalingState = {
  unkown: 0,
  stable: 1,
  haveLocalOffer: 2,
  haveRemoteOffer: 3,
  answerCreated: 4,
  furtherNegotiation: 5
}

export const eSwarmState = {
  active: 0,
  idle: 1
}
export const eRTCExtraDataType = {
  sdp: 0,
  data: 1
}

export const eSwarmAuthRequirement = {
open : 0,
PSK_ZK: 1
}

/**
 * Enum for sorting blocks
 * @readonly
 * @enum {number}
 */
export const eSortBlocksBy = {
  timestampAsc: 0,
  timestampDesc: 1,
  heightAsc: 2,
  heightDesc: 3,
  keyHeightAsc: 4,
  keyHeightDesc: 5,
  transactionsCountAsc: 6,
  transactionsCountDesc: 7,
  totalRewardAsc: 8,
  totalRewardDesc: 9,
  minerAsc: 10,
  minerDesc: 11,
  sizeAsc: 12,
  sizeDesc: 13,
  difficultyAsc: 14,
  difficultyDesc: 15
};

/**
 * Enum for sorting transactions
 * @readonly
 * @enum {number}
 */
export const eSortTransactionsBy = {
  timestampAsc: 0,
  timestampDesc: 1,
  valueAsc: 2,
  valueDesc: 3,
  statusAsc: 4,
  statusDesc: 5,
  blockHeightAsc: 6,
  blockHeightDesc: 7,
  ergUsedAsc: 8,
  ergUsedDesc: 9,
  senderAsc: 10,
  senderDesc: 11,
  nonceAsc: 12,
  nonceDesc: 13,
  sacrificialValueAsc: 14,
  sacrificialValueDesc: 15
};

/**
 * Enum for blockchain liveness states
 * @readonly
 * @enum {number}
 */
export const eLivenessState = {
    noLiveness: 0,
    lowLiveness: 1,
    mediumLiveness: 2,
    highLiveness: 3
};

/**
 * Enum for describing transaction type
 * @readonly
 * @enum {number}
 */
export const eTXType = {
  transfer: 0, // [‘Transfer’ in UI]. Invocation of regular ‘send’ GridScript command.
  blockReward: 1,// [‘Mined’ in UI]. Block reward.
  offChain: 2, // [‘Instant’ in UI]. An off-the-chain transfer from a Token Pool.
  offChainCashOut: 3, // [‘instant (completed)’ in UI]. An on-the-chain cash-out of a Transmission Token.
  contract: 4,// [‘Contract’ in UI]. An on-the-chain transfer, smart-contract evoked.
  random:99 // for testing only - used by testing UI dApp
};

export const eSearchResultElemType =
{
      TRANSACTION: 0,
      BLOCK: 1,
      DOMAIN: 2
}

export const eBlockType=
{
   keyBlock:0,
   dataBlock:1
}






export const eSwarmPeerStatus =
{
  active:0,
  notReachable:1
}

export const eConnQuality =
{
  none:0,
  low:1,
  medium:2,
  high:3,
  max:4
}


export const eSwarmMsgType = {
  keepAlive: 0,
  binary: 1,
  text: 2,
  file: 3,
  typing: 4,
  avatar: 5,
  command: 6,
  mutedAudio: 7,
  unmutedAudio: 8,
  mutedCam: 9,
  unmutedCam: 10,
  startedScreenSharing: 11,
  stoppedScreenSharing: 12,
  authenticationRequestVal: 13,
  /* <- issued by a Validator.
   ^ the above AUTH request is issued two times. 1) First by a validator who so indicates that the other peer needs to authenticate.
                             At this time, IV1 *CANNOT* be delivered.
                          2) Second, the above is issued for the second time (after authenticationRequestCand with IV2 was delivered).
                             This time 'authenticationRequestVal' contains IV1 (generated by validator).

   */
  authenticationRequestCand: 14, //<- issued by a Candidate who proposed IV2  (authenticationRequestCand) immediatedly upon reception of authenticationRequestVal with an empty IV1.
  // authenticationRequestCand contains IV2.
  authenticationSuccess: 15,
  authenticationFailure: 16,
  zeroKnowledgeProof: 17
}

export const eConnCapabilities = {
  data: 0,
  audio: 1,
  video: 2,
  audioVideo: 3
}

export const eMinecraftMsgType = {
  ping: 0, //boards player's position, nickname and current transmission token
  ready: 1, //sent by full-node when ready to receive ping messages
  failure: 2, //ex. when token-pool depleted or no longer available. may include additional info.
  exit: 3,
  goldVeinInfo: 4,
  collected: 5, //confirms collected hash, which is when new vein is generated
  newVein: 6, //collection confirmed by full-node, new vein available
  processingOfGold: 7
};

export const eTaskbarElementState = {
  active: 0,
  inactive: 1
};

export const eTaskbarElementViewState = {
  hovered: 0,
  idle: 1
};

export const eIconSize = {
  small: 0,
  normal: 1,
  large: 2
};

export const eIconsSortMode = {
  name: 0,
  size: 1,
  type: 2
};


export const eLogEntryType = {
  notification: 0, //*WARNING: KEEP THIS ITEM FIRST* <- used by iterators
  warning: 1,
  failure: 2,
  unknown: 3 //*WARNING: KEEP THIS ITEM LAST* <- used by iterators
};
export const eBlockchainMode = {
  LIVE: 0,
  TestNet: 1,
  LIVESandBox: 2, //without access to SolidStorage at all.//refreshed on demand.
  TestNetSandBox: 3, //without access to SolidStorage at all.//refreshed on demand
  LocalData: 4,
  Unknown: 5
};
export const eSwarmCmdProcessingResult = {
  unknown: 0,
  success: 1,
  invalidInThisContext: 2, //dispatch to the network.
  invalid: 3, //invalid semantics
  failure: 4 //errored; valid semantics.
}
export const eSwarmAuthMode = {
  none: 0,
  preSharedSecret: 1,
  signature: 2
}

export const eSwarmAuthResult = {
  failure: 0,
  success: 1
}

export const eLogEntryCategory = {
  network: 0, //*WARNING: KEEP THIS ITEM FIRST* <- used by iterators
  localSystem: 1,
  VM: 2,
  debug: 3, //DISABLED by default (performance)
  unknown: 4, //*WARNING: KEEP THIS ITEM LAST* <- used by iterators
  dApp: 5 //app level events
};

export const eFMUploadView = {
  modeSelector: 0,
  rewardSelector: 1,
  confirmation: 2
};
export const eVMState = {
  initializing: 0,
  ready: 1,
  aboutToShutDown: 2,
  disabled: 3,
  limitReached: 4,
  errored: 5,
  synced: 6,
  newPerspectiveAvailable: 7
};

export const eConsensusTaskType = {
  DFS: 0,
  readyForCommit: 1,
  commitAborted: 2,
  threadCommitted: 3,
  threadCommitPending: 4
};


export const eVMMetaProcessingResult = {
  success: 0,
  failure: 1
};

export const eUIAIWindowVPos = {
  top: 0,
  middle: 1,
  bottom: 2
};

export const eSound = {
  jelly: '/sounds/jelly.m4a',
  minimize: '/sounds/minimize.mp3',
  maximize: '/sounds/maximize.mp3',
  VMLoading: '/sounds/bootingup.mp3',
  VMLoaded: '/sounds/minimize.mp3',
  connecting: '/sounds/connecting.mp3',
  bootingUP: '/sounds/booting.mp3',
  welcome: '/sounds/welcome2.mp3',
  open: '/sounds/open.mp3',
  beep: '/sounds/beep.mp3',
  bleep: '/sounds/bleep.mp3',
  close: '/sounds/close.mp3',
  slide: '/sounds/slide.mp3',
  magicHover: '/sounds/magic3.mp3',
  sent: '/sounds/sent.mp3',
  bells: '/sounds/bootingup.mp3',
  ghost: '/sounds/ghost.mp3',
  transform: '/sounds/transform.mp3'
};

export const eVMMetaCodeExecutionMode = {
  RAW: 0,
  RAWDetached: 1, //creates a new worker thread; alive during particular code-package execution only.
  GUI: 2,
  GUITerminal: 3
};

export const eWindowVisibilityState = {
  initial: 0,
  maximized: 1,
  minimized: 2,
  userDefinedSize: 3,
  closed: 4,
  maximizedLeft: 5,
  maximizedRight: 6
};
export const eSDPEntityType = {

  joining: 0, //peer issued
  bye: 1, //peer issued
  getOffer: 2, //full-node issued. The full node asks existing swarm members to prepare an invitation
  processOffer: 3, //peer-issued, routed
  processOfferResponse: 4,
  processICE: 5, //peer-issued, routed
  control: 6, //full-node issued (further info within eSDPControlStatus)
  data: 7,
  pingFullNode: 8,
  pingClient: 9
};
export const eIdentityTokenType = 
{
identityOnly : 0,
PoW : 1,
Stake : 2,
Hybrid : 3,
Basic : 4
}
export const eSDPControlStatus = {
  ok: 0,
  joined: 1,
  kickedOut: 2,
  error: 3,
  invalidIdentity: 4,
  banned: 5,
  nodeLimitsExceeded: 6,
  swarmClosing: 7,
  xToOtherFullNode: 8 //propsal of other full-node included in meta-data
};
export const eConnectionState = {
  disconnected: 0,
  connecting: 1,
  connected: 2,
  aboutToShutDown: 3
};

export const eFieldValidatorType = {
  numerical: 'numType',
  alphaNumerical: 'alphaNumType',
  alpha: 'alphaType',
  address: 'addressType',
  email: 'emailType'
}

export const eWindowOverflowMode = {
  auto: 0,
  hidden: 1
}

export const eTerminalDataType = {
  input: 0,
  output: 1,
  windowDimensions: 2
}


export const eNetEntType = { //>256 - application specific
  unknown: 0,
  block: 1,
  transaction: 2,
  verifiable: 3,
  msg: 4,
  chainProof: 5,
  longestPath: 6,
  sec: 7,
  receiptBody: 8,
  receiptID: 9,
  ping: 10,
  hello: 11, //contains client information, version etc.
  bye: 12,
  QRIntentResponse: 13,
  DFS: 14,
  VMStatus: 15,
  ConnectionStatus: 16,
  VMMetaData: 17, //these might facilitate arbitrary two way communication
  //between the Full-Node and ECMA6(JavaScript) Context. ex. chalange-response communication etc.
  Swarm: 18,
  NetMsg: 19, //tuneling
  OperationStatus: 20,
  sessionInfo: 21,
  wrapper: 22
};

export const eReqDataType = {
  text: 0,
  number: 1,
  binary: 2
};

export const eDataRequestType = { //the data request VMmetasection is NOT used for State-Less Channels, which have a section type of their own.
  unknown: 0,
  QRIntentAuth: 1,
  showRAWData: 2,
  string: 3,
  integer: 4,
  binary: 5,
  boolean: 6,
  banksAuth: 7, //the token-pool's id is delivered within the default-value field,
  tokenPoolGeneration: 8,
  copyToClipboard: 9,
  password: 10,  // Added for keychain unlock prompts
  signature: 11, // Added for returning signature data
  error: 12     // Added for returning error messages
};

export const eOperationStatus = {
  success: 0,
  failure: 1,
  inProgress: 2,
  interrupted: 3
};

export const eOperationScope = {
  dataTransit: 0, //the operation is/was just about data-delivery
  peer: 1, //local peer scope
  VM: 2, //decentralized VM scope
  other: 3,
  Consensus: 4

};

export const eNetReqType = {
  unknown: 0,
  notify: 1,
  request: 2,
  process: 3,
  route: 4
};

export const eCommitState = {
  none: 0,
  prePending: 1, //local mutex-locked (VMContext strives to prevent other apps from aborting the process during the time-lock)
  pending: 2, // the commit operation has been confrimed by the full-node already. It may now be aborted by user through the Magic Button or, when something goes wrong;-  by a full node
  aborted: 3,
  success: 4, //confirmation deliverd by full-node handling the Commit Process
}

export const eDFSCmdType = {
  unknown: 0,
  init: 1, //initiates decentralized file-sub system
  ready: 2, //ready-indicator
  error: 3, //error - more info in mData1
  exists: 4, // check if path exists
  stat: 5,
  execute: 6, //executes dApp
  readDir: 7, //list directory content (LS)
  readFile: 8, //retrieve file ; path in mData1 (less)
  writeFile: 9, //write file; path in mData1:  content in mData2 (cat)
  rename: 10, //rename file/dir. pathA in mData1:  pathB in mData2
  copy: 11, //copy file/dir. pathA in mData1:  pathB in mData2
  unlink: 12,
  search: 13, //find file/dir. Regex in mData1
  touch: 14,
  sessionStat: 15,
  requestCommit: 16, //request QRIntent
  QRIntentData: 17, //serialized QRIntent in mData1
  commit: 18, //provide serialized QRIntentResponse in mData1
  //content retrieval:
  fileContent: 19, // file path in mData1:  contant in mData2
  directoryContent: 20, //sequence of vectors in mData1
  enterDir: 21, //enters StateDomain/directory (cd)
  createDir: 22,
  sync: 23,
  commitSuccess: 24,
  syncSuccess: 25,
  enterDirLS: 26,
  commitPending: 27,
  commitAborted: 28
};

// Enums for market data operations
export const eMarketSortType = {
	none: 0, 
    balance: 1,     // Sort by domain balance
    received: 2,    // Sort by total GNC received
    sent: 3,        // Sort by total GNC sent
    outgoing: 4,    // Sort by number of outgoing transactions
    incoming: 5,    // Sort by number of incoming transactions
	total: 6,    	// Sort by number of outgoing transactions
    locked: 7,      // Sort by amount of locked assets
	mined:8  		// Sort by amount of mined GNC
};

export const eSortOrder = {
    ascending: 0,   // Sort in ascending order (default)
    descending: 1   // Sort in descending order
};


export const eNotificationType = {
  unknown: 0,
  notification: 1,
  warning: 2,
  error: 3,
  binary: 4,
  copyToClipboard: 5
};

export const eDataType = {
  signedInteger: 0,
  unsignedInteger: 1,
  booll: 2,
  charr: 3,
  doublee: 4,
  bytes: 5,
  pointer: 6,
  noData: 7,
  directory: 8,
  BigInt: 9,
  BigSInt: 10,
  BigDouble: 11,
};

export const eDFSElementType = {
  unknown: 0,
  stateDomainEntry: 1,
  fileEntry: 2,
  directoryEntry: 3,
  fileContent: 4,
};

export const eWebSocketProcessingResult = {
  OK: 0,
  invalidPacket: 1,
  invalidService: 2,
  invalidSession: 3

};

export const eFSCmdResult = {
  unknown: 0,
  error: 1,
  invalidCmd: 2,
  Ok: 3
}

export const eFSCommitResult = {
  unknown: 0,
  error: 1,
  Ok: 2
}

export const eFSEntityType = {
  unknown: 0,
  file: 1,
  dir: 2
}
// DFS elements have their own VM-Meta Sections. That's for backwards compatbility.
//any new protocol should have its own VMMetaSectionType
export const eVMMetaSectionType = {
  unknown: 0,
  directoryListing: 1, //DFS
  fileContents: 2, //DFS
  notifications: 3,
  requests: 4,
  stateLessChannels: 5, //used for OBJECTS' deliveries. requests for token pool generation etc are carried out through data-request VMMetaData
  statistics: 6,
  responses: 7// we basically do not employ this. We use 'notifications' with a requestID set instead
  //sections/entries
}
/**
 * Enum for transaction validation results
 * @readonly
 * @enum {number}
 */
export const  eTransactionValidationResult = {
  valid: 0,
  invalid: 1,
  unknownIssuer: 2,
  insufficientERG: 3,
  ERGBidTooLow: 4,
  pubNotMatch: 5,
  noIDToken: 6,
  noPublicKey: 7,
  invalidSig: 8,
  invalidBalance: 9,
  incosistentData: 10,
  validNoTrieEffect: 11,
  invalidSacrifice: 12,
  invalidNonce: 13,
  forkedOut: 14,
  received: 15,          // Transaction received, awaiting pre-validation
  invalidBytecode: 16,   // Transaction has invalid/undecompilable byte-code
  random:99// testing only - used by Tesing UI dApp
};

/**
 * Enum for sorting blocks
 * @readonly
 * @enum {number}
 */
export const eSortBlocksByEnum = {
  timestampAsc: 0,
  timestampDesc: 1,
  heightAsc: 2,
  heightDesc: 3,
  keyHeightAsc: 4,
  keyHeightDesc: 5,
  transactionsCountAsc: 6,
  transactionsCountDesc: 7,
  totalRewardAsc: 8,
  totalRewardDesc: 9,
  minerAsc: 10,
  minerDesc: 11,
  sizeAsc: 12,
  sizeDesc: 13,
  difficultyAsc: 14,
  difficultyDesc: 15
};




export const eColor = {
  none: 0,
  lightWhite: 1,
  lightGreen: 2,
  lightCyan: 3,
  lightPink: 4,
  blue: 5,
  orange: 6,
  greyWhiteBox: 7,
  cyberWine: 8,
  lightCyberWine: 9,
  cyborgBlood: 10,
  gentlePink: 11
}

export const eMagicButtonState = {
  ready: 0,
  committing: 1,
  error: 2,
  success: 3,
  syncing: 4
}

export const eStateLessChannelsElementType = {
  token: 0,
  tokenPool: 1,
  transitPool: 2,
  receipt: 3,
  bankUpdate: 4
};
//TRIPPLE note: DFS has DFS-specific Sections, Elements AND DFS-level protocol specific entry-types (e.x. state-domain/folder/file - eDFSElementType)
// DFS elements have their own eVMMetaEntryType types. That's for backwards compatbility.
// any new protocol should have just a single eVMMetaEntryType and describe protocol specific subtypes using data-field.
export const eVMMetaEntryType = {
  unknown: 0,
  directoryEntry: 1, //DFS - then it might be any eDFSElementType::eDFSElementType within desribed using protocol-level data-fields
  //TRIPPLE note: DFS has DFS-specific Sections, Elements AND DFS-level protocol specific entry-types (e.x. state-domain/folder/file - eDFSElementType)
  fileContent: 2,
  notification: 3,
  dataRequest: 4, // ex. used to request delivery  of TP's banks' auth data from mobile app by the UI; Full-node: used to request a  dialog box asking for a String to be shown to user
  dataResponse: 5, // ex. used for deliveries of updates to the Token-Pool's banks by the mobile app  to web-ui; used to deliver String previously asked for by full-node from web-ui
  GridScriptCode: 6,
  GridScriptCodeResponse: 7,
  terminalData: 8,
  StateLessChannelsElement: 9,
  appNotification: 10,
  VMStatus: 11,
  threadOperation: 12,
  consensusTask: 13,
  txProof: 14,
  // Blockchain Explorer - BEGIN
  
  // History - BEGIN
  transactionsHistory: 15,
  blocksHistory: 16,
  // History - END
  
  // Details - BEGIN
  transactionDetails: 17,
  blockDetails: 18,
  domainDetails: 19,
  // Details - END
  
  searchResults: 20,
  blockchainHeight: 21, //both key and data
  usdtPrice: 22,
  livenessInfo: 23,
  blockchainStatus: 24,
  transactionDailyStats: 25,
  marketDepth: 26, // 'market' GridScript command
  preCompiledTransaction: 27 // For submitting locally compiled and signed transactions
  // Blockchain Explorer - END
};

export const eTokenPoolBankStatus = {
  active: 0,
  depleted: 1
}

export const eTokenPoolStatus = {
  active: 0,
  depleted: 1,
  banned: 2
}

export const eChannelLocalPingType = {
  lastUpdate: 0,
  lastUsed: 1,
  lastCashOut: 2,
  lastSync: 3
}

export const eChannelDirection = {
  ingress: 0,
  outgress: 1,
  both: 2
}

export const eAddressType = {
  IPv4: 0,
  IPv6: 1,
  MAC: 2,
  PeerID: 3,
  TerminalID: 4
};


export const eEndpointType = {
  IPv4: 0,
  IPv6: 1,
  MAC: 2,
  PeerID: 3,
  TerminalID: 4,
  WebSockConversation: 5,
  UDTConversation: 6,
  WebRTCSwarm: 7,
  VM: 8
};


export const eThreadOperationType = {
  newThread: 0,
  freeThread: 1,
  threadAliveConfirmation: 2,
  threadKilledConfirmation: 3
}

export const eUITTaskType = {
  notification: 0,
  request: 1
}

export const eGUITaskState = {
  initial: 0,
  enqued: 1,
  alreadyShown: 2,
  canceledByUser: 3,
  accomplished: 4,
  failed: 5
}

export const eContextState = {
  initial: 0,
  activating: 1,
  active: 2,
  inactive: 3
}
